// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTunnel():Promise<void>;

export function DummySec():Promise<Array<main.SectionInfo>>;

export function GetConfig():Promise<main.Config>;

export function GetPaymentNetworkWalletAddr():Promise<string>;

export function GetProxyAddr():Promise<string>;

export function GetTunnelEnabled():Promise<boolean>;

export function SaveTunnelConfig(arg1:number,arg2:boolean,arg3:string):Promise<string>;

export function ShowWarnMsg(arg1:string):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;
